DROP TABLE IF EXISTS Bundle;
DROP TABLE IF EXISTS BoosterPack;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS UserBundle;

CREATE TABLE User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50),
    Age INT,
    Email VARCHAR(100)
);